/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as HoustonRouteImport } from './routes/houston'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebsitesRouteImport } from './routes/services.websites'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesMobileAppsRouteImport } from './routes/services.mobile-apps'
import { Route as ServicesCloudHostingRouteImport } from './routes/services.cloud-hosting'
import { Route as ServicesBrandingRouteImport } from './routes/services.branding'
import { Route as HoustonCityRouteImport } from './routes/houston.$city'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const HoustonRoute = HoustonRouteImport.update({
  id: '/houston',
  path: '/houston',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsitesRoute = ServicesWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMobileAppsRoute = ServicesMobileAppsRouteImport.update({
  id: '/mobile-apps',
  path: '/mobile-apps',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCloudHostingRoute = ServicesCloudHostingRouteImport.update({
  id: '/cloud-hosting',
  path: '/cloud-hosting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBrandingRoute = ServicesBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ServicesRoute,
} as any)
const HoustonCityRoute = HoustonCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => HoustonRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/houston': typeof HoustonRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/houston/$city': typeof HoustonCityRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/websites': typeof ServicesWebsitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/houston': typeof HoustonRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/houston/$city': typeof HoustonCityRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/websites': typeof ServicesWebsitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/houston': typeof HoustonRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/houston/$city': typeof HoustonCityRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/mobile-apps': typeof ServicesMobileAppsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/websites': typeof ServicesWebsitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/houston'
    | '/services'
    | '/sitemap.xml'
    | '/work'
    | '/houston/$city'
    | '/services/branding'
    | '/services/cloud-hosting'
    | '/services/mobile-apps'
    | '/services/seo'
    | '/services/websites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/houston'
    | '/services'
    | '/sitemap.xml'
    | '/work'
    | '/houston/$city'
    | '/services/branding'
    | '/services/cloud-hosting'
    | '/services/mobile-apps'
    | '/services/seo'
    | '/services/websites'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/houston'
    | '/services'
    | '/sitemap.xml'
    | '/work'
    | '/houston/$city'
    | '/services/branding'
    | '/services/cloud-hosting'
    | '/services/mobile-apps'
    | '/services/seo'
    | '/services/websites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HoustonRoute: typeof HoustonRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houston': {
      id: '/houston'
      path: '/houston'
      fullPath: '/houston'
      preLoaderRoute: typeof HoustonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/websites': {
      id: '/services/websites'
      path: '/websites'
      fullPath: '/services/websites'
      preLoaderRoute: typeof ServicesWebsitesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile-apps': {
      id: '/services/mobile-apps'
      path: '/mobile-apps'
      fullPath: '/services/mobile-apps'
      preLoaderRoute: typeof ServicesMobileAppsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-hosting': {
      id: '/services/cloud-hosting'
      path: '/cloud-hosting'
      fullPath: '/services/cloud-hosting'
      preLoaderRoute: typeof ServicesCloudHostingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/branding': {
      id: '/services/branding'
      path: '/branding'
      fullPath: '/services/branding'
      preLoaderRoute: typeof ServicesBrandingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/houston/$city': {
      id: '/houston/$city'
      path: '/$city'
      fullPath: '/houston/$city'
      preLoaderRoute: typeof HoustonCityRouteImport
      parentRoute: typeof HoustonRoute
    }
  }
}

interface HoustonRouteChildren {
  HoustonCityRoute: typeof HoustonCityRoute
}

const HoustonRouteChildren: HoustonRouteChildren = {
  HoustonCityRoute: HoustonCityRoute,
}

const HoustonRouteWithChildren =
  HoustonRoute._addFileChildren(HoustonRouteChildren)

interface ServicesRouteChildren {
  ServicesBrandingRoute: typeof ServicesBrandingRoute
  ServicesCloudHostingRoute: typeof ServicesCloudHostingRoute
  ServicesMobileAppsRoute: typeof ServicesMobileAppsRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesWebsitesRoute: typeof ServicesWebsitesRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBrandingRoute: ServicesBrandingRoute,
  ServicesCloudHostingRoute: ServicesCloudHostingRoute,
  ServicesMobileAppsRoute: ServicesMobileAppsRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesWebsitesRoute: ServicesWebsitesRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HoustonRoute: HoustonRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
